### ISSUE TITLE
Froze Ledger Nano X

### ISSUE THREAD

**Issue by kphed** [celo-org/celo-ledger-spender-app#13]
I was able to install the app on my Ledger Nano X via Ledger Live's Manager and have it be recognized by a local Geth instance. However, after opening it a few times, the device froze (i.e.unable to exit the Celo spender app nor shut off the device) on the "Pending Ledger Review" screen. I haven't had any issues using the app with my Nano S and it's been functioning flawlessly (awesome work). My suspicion is that the BOLOS SDK isn't fully compatible with Nano X devices yet as it's not even mentioned in the [docs](https://ledger.readthedocs.io/en/latest/userspace/getting_started.html).

**Comment by kobigurk** [comment]
Hey @kphed, thanks for this! We're aware and checking it with the Ledger team.

**Comment by zviadm** [comment]
Same issue here. This is especially problematic on Nano X because it is battery powered so I am not sure i can even reset it manually, so it is just bricked at the moment.
![image](https://user-images.githubusercontent.com/517937/81407611-b7a50580-9109-11ea-9263-a311b80675f9.png)

**Comment by kobigurk** [comment]
Hey @zviadm, have you tried holding both buttons for a few seconds? It should bring you back to the control center.

In any case, a new version will be released that will not have that screen, which we hope will solve the issue.

**Comment by zviadm** [comment]
> Hey @zviadm, have you tried holding both buttons for a few seconds? It should bring you back to the control center.
> 
> In any case, a new version will be released that will not have that screen, which we hope will solve the issue.

No, holding both buttons doesn't work, since it looks like device is completely frozen. So it is fully inoperable. Luckily I do have a backup Nano S and since it isn't battery powered it can be reset by unplugging and plugging back in. (However I have definitely frozen Nano S in similar way too,  I dont have an exact repro though unfortunately.)

**Comment by nambrot** [comment]
I think one thing that anecdotally I have heard works is to wait for a second or two before proceeding to the next screen by pressing both buttons

**Comment by kobigurk** [comment]
Closing since the screen was removed and a doc section was added.
